name: nox

on: [push, pull_request]

jobs:
  generate-test-jobs:
    runs-on: ubuntu-latest
    outputs:
      session: ${{ steps.set-matrix.outputs.session }}
    steps:
      - uses: actions/checkout@v3
      - uses: wntrblm/nox@main
      - id: set-matrix
        shell: bash
        run: echo session=$(nox -s tests --json -l | jq -c '[.[].session]') | tee --append $GITHUB_OUTPUT
  test:
    name: ${{ matrix.session }}
    needs: [generate-test-jobs]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        session: ${{ fromJson(needs.generate-test-jobs.outputs.session) }}
    steps:
      - uses: actions/checkout@v3
      - uses: wntrblm/nox@main
      - run: nox -s "${{ matrix.session }}" -- --cov-branch --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: unittests
          verbose: true

  #     - name: Save coverage reports
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: coverage-${{ github.job }}-${{ strategy.job-index }}
  #         path: .coverage
  #         include-hidden-files: true
  #         if-no-files-found: error

  # coverage:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Upload coverage to Codecov
  #       uses: codecov/codecov-action@v4
  #       with:
  #         token: ${{ secrets.CODECOV_TOKEN }}
  #         fail_ci_if_error: true
  #         files: .coverage
  #         flags: unittests
  #         name: codecov-umbrella
  #         verbose: true

  generate-build-jobs:
    runs-on: ubuntu-latest
    outputs:
      session: ${{ steps.set-matrix.outputs.session }}
    steps:
      - uses: actions/checkout@v3
      - uses: wntrblm/nox@main
      - id: set-matrix
        shell: bash
        run: echo session=$(nox -s build --json -l | jq -c '[.[].session]') | tee --append $GITHUB_OUTPUT
  build:
    name: ${{ matrix.session }}
    needs: [generate-build-jobs]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        session: ${{ fromJson(needs.generate-build-jobs.outputs.session) }}
    steps:
      - uses: actions/checkout@v3
      - uses: wntrblm/nox@main
      - run: nox -s "${{ matrix.session }}"
